"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bookmark, BookmarkCheck, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { cn, safeJson } from "@/lib/utils";

type VoiceProfile = {
  traits: string[];
  summary?: string | null;
};

type Idea = {
  hook: string;
  expansion: string;
  type: "Opinion" | "Story" | "Tip" | "Data" | "Question";
  soundsLikeUser: boolean;
};

type MeResponse = {
  user?: {
    topics?: string[];
    voiceProfile?: VoiceProfile | null;
  };
};

type IdeasResponse = {
  ideas?: Idea[];
  error?: string;
};

const defaultTopics = [
  "Personal brand",
  "Audience growth",
  "Content strategy",
  "Founder lessons",
  "Career growth",
  "Systems",
  "Leadership",
  "Storytelling",
];

function toTitleCase(value: string) {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1).toLowerCase())
    .join(" ");
}

function dedupeTopics(topics: string[]) {
  return [...new Set(topics.map((topic) => topic.trim()).filter(Boolean))].slice(0, 8);
}

function buildSuggestedTopics(profile: VoiceProfile | null) {
  if (!profile?.traits?.length) {
    return defaultTopics.slice(0, 8);
  }

  const traitMap: Record<string, string[]> = {
    analytical: ["Data", "Strategy", "Systems"],
    storyteller: ["Founder stories", "Behind the scenes", "Career moments"],
    conversational: ["Communication", "Personal brand", "Lessons learned"],
    direct: ["Execution", "Decisions", "Leadership"],
    hookfirst: ["Contrarian takes", "Hard truths", "Unpopular opinions"],
    "hook-first": ["Contrarian takes", "Hard truths", "Unpopular opinions"],
    opinionated: ["Industry takes", "Hot takes", "What most people miss"],
    reflective: ["Lessons learned", "Career growth", "Founder lessons"],
    educational: ["How-to posts", "Frameworks", "Tips"],
  };

  const normalizedTraits = profile.traits.map((trait) => trait.toLowerCase().replace(/\s+/g, ""));
  const suggested = normalizedTraits.flatMap((trait) => traitMap[trait] ?? []);

  return dedupeTopics([...suggested, ...defaultTopics]);
}

async function readError(response: Response, fallback: string) {
  try {
    const data = (await response.json()) as { error?: string };
    return data.error ?? fallback;
  } catch {
    return fallback;
  }
}

export function IdeasClient({ embedded = false }: { embedded?: boolean }) {
  const router = useRouter();
  const autoGeneratedRef = useRef(false);
  const [voiceProfile, setVoiceProfile] = useState<VoiceProfile | null>(null);
  const [selectedTopics, setSelectedTopics] = useState<string[]>([]);
  const [topicInput, setTopicInput] = useState("");
  const [ideas, setIdeas] = useState<Idea[]>([]);
  const [savedHooks, setSavedHooks] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [bootstrapping, setBootstrapping] = useState(true);

  useEffect(() => {
    let active = true;

    fetch("/api/me")
      .then((response) => safeJson<MeResponse>(response))
      .then((data) => {
        if (!active) return;
        setVoiceProfile(data.user?.voiceProfile ?? null);
        setSelectedTopics(dedupeTopics(data.user?.topics ?? []));
      })
      .catch(() => {
        if (!active) return;
        toast.error("Unable to load your topic settings.");
      })
      .finally(() => {
        if (active) setBootstrapping(false);
      });

    return () => {
      active = false;
    };
  }, []);

  const suggestedTopics = useMemo(() => buildSuggestedTopics(voiceProfile), [voiceProfile]);
  const topicOptions = useMemo(
    () => dedupeTopics([...selectedTopics, ...suggestedTopics]),
    [selectedTopics, suggestedTopics]
  );

  async function persistTopics(nextTopics: string[]) {
    const normalized = dedupeTopics(nextTopics);
    const previousTopics = selectedTopics;
    setSelectedTopics(normalized);

    try {
      const response = await fetch("/api/user/topics", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topics: normalized }),
      });

      if (!response.ok) {
        throw new Error(await readError(response, "Unable to save topics"));
      }
    } catch (error) {
      setSelectedTopics(previousTopics);
      toast.error(error instanceof Error ? error.message : "Unable to save topics");
    }
  }

  function toggleTopic(topic: string) {
    const normalized = toTitleCase(topic);
    if (selectedTopics.includes(normalized)) {
      void persistTopics(selectedTopics.filter((item) => item !== normalized));
      return;
    }

    if (selectedTopics.length >= 8) {
      toast.error("You can save up to 8 topics.");
      return;
    }

    void persistTopics([...selectedTopics, normalized]);
  }

  function addCustomTopic() {
    const normalized = toTitleCase(topicInput);
    if (!normalized) return;
    if (selectedTopics.includes(normalized)) {
      setTopicInput("");
      return;
    }
    if (selectedTopics.length >= 8) {
      toast.error("You can save up to 8 topics.");
      return;
    }

    setTopicInput("");
    void persistTopics([...selectedTopics, normalized]);
  }

  const requestIdeas = useCallback(
    async (topics = selectedTopics) => {
      if (!voiceProfile) return;
      if (topics.length === 0) {
        toast.error("Select at least one topic first.");
        return;
      }

      setLoading(true);

      try {
        const response = await fetch("/api/ideas/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ topics }),
        });

        if (!response.ok) {
          throw new Error(await readError(response, "Unable to generate ideas"));
        }

        const data = (await response.json()) as IdeasResponse;
        setIdeas(data.ideas ?? []);
      } catch (error) {
        toast.error(error instanceof Error ? error.message : "Unable to generate ideas");
      } finally {
        setLoading(false);
      }
    },
    [selectedTopics, voiceProfile]
  );

  useEffect(() => {
    if (bootstrapping || autoGeneratedRef.current || !voiceProfile || selectedTopics.length === 0) {
      return;
    }

    autoGeneratedRef.current = true;
    void requestIdeas(selectedTopics);
  }, [bootstrapping, requestIdeas, selectedTopics, voiceProfile]);

  async function saveIdea(idea: Idea) {
    if (savedHooks.includes(idea.hook)) return;

    try {
      const response = await fetch("/api/ideas/save", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(idea),
      });

      if (!response.ok) {
        throw new Error(await readError(response, "Unable to save idea"));
      }

      setSavedHooks((current) => [...current, idea.hook]);
      toast.success("Idea saved.");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Unable to save idea");
    }
  }

  function startFromIdea(idea: Idea) {
    router.push(`/compose?idea=${encodeURIComponent(idea.hook)}`);
  }

  return (
    <section className="space-y-6">
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <h1 className={cn("font-semibold text-ink", embedded ? "text-xl" : "text-2xl")}>
            {embedded ? "Post ideas" : "Ideas"}
          </h1>
          <p className="mt-1 text-sm text-muted">
            Use your Voice DNA and favorite topics to generate sharper LinkedIn angles on demand.
          </p>
        </div>

        <Button onClick={() => void requestIdeas()} disabled={loading || !voiceProfile}>
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Generating...
            </>
          ) : (
            "Generate 5 ideas →"
          )}
        </Button>
      </div>

      {!voiceProfile ? (
        <div className="quill-card p-6">
          <div className="rounded-xl border border-dashed border-brand/30 bg-brand-light/40 p-5 text-sm leading-6 text-muted">
            Set up your Voice DNA first to get ideas in your voice.{" "}
            <Link href="/voice-dna" className="font-medium text-brand hover:underline">
              Go to Voice DNA
            </Link>
          </div>
        </div>
      ) : (
        <>
          <div className="quill-card p-6">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h2 className="text-lg font-semibold text-ink">Topic setup</h2>
                <p className="mt-1 text-sm text-muted">
                  Pick up to 8 themes you want Quill to generate ideas around.
                </p>
              </div>
              <div className="rounded-full bg-brand-light px-3 py-1 text-xs font-medium text-brand">
                {selectedTopics.length} / 8 selected
              </div>
            </div>

            <div className="mt-5 flex flex-wrap gap-2">
              {topicOptions.map((topic) => {
                const selected = selectedTopics.includes(topic);
                return (
                  <button
                    key={topic}
                    type="button"
                    onClick={() => toggleTopic(topic)}
                    className={cn(
                      "rounded-full border px-3 py-1.5 text-sm font-medium transition",
                      selected
                        ? "border-brand bg-brand text-white"
                        : "border-brand/20 bg-white text-brand hover:bg-brand-light"
                    )}
                  >
                    {topic}
                  </button>
                );
              })}
            </div>

            <div className="mt-5 flex flex-col gap-3 sm:flex-row">
              <input
                value={topicInput}
                onChange={(event) => setTopicInput(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.preventDefault();
                    addCustomTopic();
                  }
                }}
                className="quill-input flex-1"
                placeholder="Add a custom topic"
              />
              <Button variant="outline" onClick={addCustomTopic}>
                Add topic
              </Button>
            </div>
          </div>

          <div className="space-y-4">
            {bootstrapping ? (
              <div className="quill-card p-6">
                <div className="flex items-center gap-3 text-sm text-muted">
                  <Loader2 className="h-4 w-4 animate-spin text-brand" />
                  Loading your topic setup...
                </div>
              </div>
            ) : ideas.length === 0 ? (
              <div className="quill-card p-10 text-center">
                <Sparkles className="mx-auto h-8 w-8 text-brand" />
                <p className="mt-4 text-base font-medium text-ink">
                  {selectedTopics.length === 0
                    ? "Choose a few topics to start generating ideas."
                    : "No ideas yet. Generate a fresh batch to fill your feed."}
                </p>
                <p className="mt-2 text-sm text-muted">
                  Quill will match the hooks to your voice profile so the ideas already sound like
                  you.
                </p>
              </div>
            ) : (
              <div className="grid gap-4 lg:grid-cols-2">
                {ideas.map((idea) => {
                  const saved = savedHooks.includes(idea.hook);
                  return (
                    <div key={`${idea.type}-${idea.hook}`} className="quill-card p-5">
                      <div className="flex items-center justify-between gap-3">
                        <span className="rounded-full bg-brand-light px-3 py-1 text-xs font-medium text-brand">
                          {idea.type}
                        </span>
                        <div className="flex items-center gap-2 text-xs text-muted">
                          <span
                            className={cn(
                              "h-2.5 w-2.5 rounded-full",
                              idea.soundsLikeUser ? "bg-emerald-500" : "bg-slate-300"
                            )}
                          />
                          {idea.soundsLikeUser ? "Sounds like you" : "Generic tone"}
                        </div>
                      </div>

                      <h3 className="mt-4 text-base font-semibold leading-7 text-ink">
                        {idea.hook}
                      </h3>
                      <p className="mt-2 text-sm leading-6 text-muted">{idea.expansion}</p>

                      <div className="mt-5 flex items-center justify-between gap-3">
                        <button
                          type="button"
                          onClick={() => startFromIdea(idea)}
                          className="text-sm font-medium text-brand hover:underline"
                        >
                          Use this idea →
                        </button>
                        <button
                          type="button"
                          onClick={() => void saveIdea(idea)}
                          className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-line text-muted transition hover:border-brand/20 hover:text-brand"
                          aria-label={saved ? "Idea saved" : "Save idea"}
                        >
                          {saved ? (
                            <BookmarkCheck className="h-4 w-4 text-brand" />
                          ) : (
                            <Bookmark className="h-4 w-4" />
                          )}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </>
      )}
    </section>
  );
}
